// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capsule8/api/v0/expression.proto

package v0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ValueType int32

const (
	ValueType_VALUETYPE_UNSPECIFIED ValueType = 0
	ValueType_STRING                ValueType = 1
	ValueType_SINT8                 ValueType = 2
	ValueType_SINT16                ValueType = 3
	ValueType_SINT32                ValueType = 4
	ValueType_SINT64                ValueType = 5
	ValueType_UINT8                 ValueType = 6
	ValueType_UINT16                ValueType = 7
	ValueType_UINT32                ValueType = 8
	ValueType_UINT64                ValueType = 9
	ValueType_BOOL                  ValueType = 10
	ValueType_DOUBLE                ValueType = 11
	ValueType_TIMESTAMP             ValueType = 12
)

var ValueType_name = map[int32]string{
	0:  "VALUETYPE_UNSPECIFIED",
	1:  "STRING",
	2:  "SINT8",
	3:  "SINT16",
	4:  "SINT32",
	5:  "SINT64",
	6:  "UINT8",
	7:  "UINT16",
	8:  "UINT32",
	9:  "UINT64",
	10: "BOOL",
	11: "DOUBLE",
	12: "TIMESTAMP",
}
var ValueType_value = map[string]int32{
	"VALUETYPE_UNSPECIFIED": 0,
	"STRING":                1,
	"SINT8":                 2,
	"SINT16":                3,
	"SINT32":                4,
	"SINT64":                5,
	"UINT8":                 6,
	"UINT16":                7,
	"UINT32":                8,
	"UINT64":                9,
	"BOOL":                  10,
	"DOUBLE":                11,
	"TIMESTAMP":             12,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (ValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type Expression_ExpressionType int32

const (
	Expression_EXPRESSIONTYPE_UNSPECIFIED Expression_ExpressionType = 0
	Expression_IDENTIFIER                 Expression_ExpressionType = 1
	Expression_VALUE                      Expression_ExpressionType = 2
	Expression_LOGICAL_AND                Expression_ExpressionType = 10
	Expression_LOGICAL_OR                 Expression_ExpressionType = 11
	Expression_EQ                         Expression_ExpressionType = 20
	Expression_NE                         Expression_ExpressionType = 21
	Expression_LT                         Expression_ExpressionType = 22
	Expression_LE                         Expression_ExpressionType = 23
	Expression_GT                         Expression_ExpressionType = 24
	Expression_GE                         Expression_ExpressionType = 25
	Expression_LIKE                       Expression_ExpressionType = 26
	Expression_IS_NULL                    Expression_ExpressionType = 27
	Expression_IS_NOT_NULL                Expression_ExpressionType = 28
	Expression_BITWISE_AND                Expression_ExpressionType = 30
)

var Expression_ExpressionType_name = map[int32]string{
	0:  "EXPRESSIONTYPE_UNSPECIFIED",
	1:  "IDENTIFIER",
	2:  "VALUE",
	10: "LOGICAL_AND",
	11: "LOGICAL_OR",
	20: "EQ",
	21: "NE",
	22: "LT",
	23: "LE",
	24: "GT",
	25: "GE",
	26: "LIKE",
	27: "IS_NULL",
	28: "IS_NOT_NULL",
	30: "BITWISE_AND",
}
var Expression_ExpressionType_value = map[string]int32{
	"EXPRESSIONTYPE_UNSPECIFIED": 0,
	"IDENTIFIER":                 1,
	"VALUE":                      2,
	"LOGICAL_AND":                10,
	"LOGICAL_OR":                 11,
	"EQ":                         20,
	"NE":                         21,
	"LT":                         22,
	"LE":                         23,
	"GT":                         24,
	"GE":                         25,
	"LIKE":                       26,
	"IS_NULL":                    27,
	"IS_NOT_NULL":                28,
	"BITWISE_AND":                30,
}

func (x Expression_ExpressionType) String() string {
	return proto.EnumName(Expression_ExpressionType_name, int32(x))
}
func (Expression_ExpressionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{2, 0} }

type Value struct {
	Type ValueType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.ValueType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Value_SignedValue
	//	*Value_UnsignedValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_DoubleValue
	//	*Value_TimestampValue
	Value isValue_Value `protobuf_oneof:"value"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type isValue_Value interface {
	isValue_Value()
}

type Value_SignedValue struct {
	SignedValue int64 `protobuf:"zigzag64,10,opt,name=signed_value,json=signedValue,oneof"`
}
type Value_UnsignedValue struct {
	UnsignedValue uint64 `protobuf:"varint,11,opt,name=unsigned_value,json=unsignedValue,oneof"`
}
type Value_StringValue struct {
	StringValue string `protobuf:"bytes,12,opt,name=string_value,json=stringValue,oneof"`
}
type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,13,opt,name=bool_value,json=boolValue,oneof"`
}
type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,14,opt,name=double_value,json=doubleValue,oneof"`
}
type Value_TimestampValue struct {
	TimestampValue *google_protobuf.Timestamp `protobuf:"bytes,15,opt,name=timestamp_value,json=timestampValue,oneof"`
}

func (*Value_SignedValue) isValue_Value()    {}
func (*Value_UnsignedValue) isValue_Value()  {}
func (*Value_StringValue) isValue_Value()    {}
func (*Value_BoolValue) isValue_Value()      {}
func (*Value_DoubleValue) isValue_Value()    {}
func (*Value_TimestampValue) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_VALUETYPE_UNSPECIFIED
}

func (m *Value) GetSignedValue() int64 {
	if x, ok := m.GetValue().(*Value_SignedValue); ok {
		return x.SignedValue
	}
	return 0
}

func (m *Value) GetUnsignedValue() uint64 {
	if x, ok := m.GetValue().(*Value_UnsignedValue); ok {
		return x.UnsignedValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetTimestampValue() *google_protobuf.Timestamp {
	if x, ok := m.GetValue().(*Value_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_SignedValue)(nil),
		(*Value_UnsignedValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_TimestampValue)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_SignedValue:
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeZigzag64(uint64(x.SignedValue))
	case *Value_UnsignedValue:
		b.EncodeVarint(11<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.UnsignedValue))
	case *Value_StringValue:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Value_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(13<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_DoubleValue:
		b.EncodeVarint(14<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Value_TimestampValue:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimestampValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 10: // value.signed_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag64()
		m.Value = &Value_SignedValue{int64(x)}
		return true, err
	case 11: // value.unsigned_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_UnsignedValue{x}
		return true, err
	case 12: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_StringValue{x}
		return true, err
	case 13: // value.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_BoolValue{x != 0}
		return true, err
	case 14: // value.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Value_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 15: // value.timestamp_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Timestamp)
		err := b.DecodeMessage(msg)
		m.Value = &Value_TimestampValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_SignedValue:
		n += proto.SizeVarint(10<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(uint64(x.SignedValue<<1) ^ uint64((int64(x.SignedValue) >> 63))))
	case *Value_UnsignedValue:
		n += proto.SizeVarint(11<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.UnsignedValue))
	case *Value_StringValue:
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Value_BoolValue:
		n += proto.SizeVarint(13<<3 | proto.WireVarint)
		n += 1
	case *Value_DoubleValue:
		n += proto.SizeVarint(14<<3 | proto.WireFixed64)
		n += 8
	case *Value_TimestampValue:
		s := proto.Size(x.TimestampValue)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BinaryOp struct {
	Lhs *Expression `protobuf:"bytes,1,opt,name=lhs" json:"lhs,omitempty"`
	Rhs *Expression `protobuf:"bytes,2,opt,name=rhs" json:"rhs,omitempty"`
}

func (m *BinaryOp) Reset()                    { *m = BinaryOp{} }
func (m *BinaryOp) String() string            { return proto.CompactTextString(m) }
func (*BinaryOp) ProtoMessage()               {}
func (*BinaryOp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *BinaryOp) GetLhs() *Expression {
	if m != nil {
		return m.Lhs
	}
	return nil
}

func (m *BinaryOp) GetRhs() *Expression {
	if m != nil {
		return m.Rhs
	}
	return nil
}

type Expression struct {
	Type Expression_ExpressionType `protobuf:"varint,1,opt,name=type,enum=capsule8.api.v0.Expression_ExpressionType" json:"type,omitempty"`
	// Types that are valid to be assigned to Expr:
	//	*Expression_Identifier
	//	*Expression_Value
	//	*Expression_BinaryOp
	//	*Expression_UnaryOp
	Expr isExpression_Expr `protobuf_oneof:"expr"`
}

func (m *Expression) Reset()                    { *m = Expression{} }
func (m *Expression) String() string            { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()               {}
func (*Expression) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type isExpression_Expr interface {
	isExpression_Expr()
}

type Expression_Identifier struct {
	Identifier string `protobuf:"bytes,10,opt,name=identifier,oneof"`
}
type Expression_Value struct {
	Value *Value `protobuf:"bytes,11,opt,name=value,oneof"`
}
type Expression_BinaryOp struct {
	BinaryOp *BinaryOp `protobuf:"bytes,12,opt,name=binary_op,json=binaryOp,oneof"`
}
type Expression_UnaryOp struct {
	UnaryOp *Expression `protobuf:"bytes,13,opt,name=unary_op,json=unaryOp,oneof"`
}

func (*Expression_Identifier) isExpression_Expr() {}
func (*Expression_Value) isExpression_Expr()      {}
func (*Expression_BinaryOp) isExpression_Expr()   {}
func (*Expression_UnaryOp) isExpression_Expr()    {}

func (m *Expression) GetExpr() isExpression_Expr {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (m *Expression) GetType() Expression_ExpressionType {
	if m != nil {
		return m.Type
	}
	return Expression_EXPRESSIONTYPE_UNSPECIFIED
}

func (m *Expression) GetIdentifier() string {
	if x, ok := m.GetExpr().(*Expression_Identifier); ok {
		return x.Identifier
	}
	return ""
}

func (m *Expression) GetValue() *Value {
	if x, ok := m.GetExpr().(*Expression_Value); ok {
		return x.Value
	}
	return nil
}

func (m *Expression) GetBinaryOp() *BinaryOp {
	if x, ok := m.GetExpr().(*Expression_BinaryOp); ok {
		return x.BinaryOp
	}
	return nil
}

func (m *Expression) GetUnaryOp() *Expression {
	if x, ok := m.GetExpr().(*Expression_UnaryOp); ok {
		return x.UnaryOp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Expression) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Expression_OneofMarshaler, _Expression_OneofUnmarshaler, _Expression_OneofSizer, []interface{}{
		(*Expression_Identifier)(nil),
		(*Expression_Value)(nil),
		(*Expression_BinaryOp)(nil),
		(*Expression_UnaryOp)(nil),
	}
}

func _Expression_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Expression)
	// expr
	switch x := m.Expr.(type) {
	case *Expression_Identifier:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Identifier)
	case *Expression_Value:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Value); err != nil {
			return err
		}
	case *Expression_BinaryOp:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BinaryOp); err != nil {
			return err
		}
	case *Expression_UnaryOp:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UnaryOp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Expression.Expr has unexpected type %T", x)
	}
	return nil
}

func _Expression_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Expression)
	switch tag {
	case 10: // expr.identifier
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Expr = &Expression_Identifier{x}
		return true, err
	case 11: // expr.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Value)
		err := b.DecodeMessage(msg)
		m.Expr = &Expression_Value{msg}
		return true, err
	case 12: // expr.binary_op
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BinaryOp)
		err := b.DecodeMessage(msg)
		m.Expr = &Expression_BinaryOp{msg}
		return true, err
	case 13: // expr.unary_op
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Expression)
		err := b.DecodeMessage(msg)
		m.Expr = &Expression_UnaryOp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Expression_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Expression)
	// expr
	switch x := m.Expr.(type) {
	case *Expression_Identifier:
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Identifier)))
		n += len(x.Identifier)
	case *Expression_Value:
		s := proto.Size(x.Value)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Expression_BinaryOp:
		s := proto.Size(x.BinaryOp)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Expression_UnaryOp:
		s := proto.Size(x.UnaryOp)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Value)(nil), "capsule8.api.v0.Value")
	proto.RegisterType((*BinaryOp)(nil), "capsule8.api.v0.BinaryOp")
	proto.RegisterType((*Expression)(nil), "capsule8.api.v0.Expression")
	proto.RegisterEnum("capsule8.api.v0.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("capsule8.api.v0.Expression_ExpressionType", Expression_ExpressionType_name, Expression_ExpressionType_value)
}

func init() { proto.RegisterFile("capsule8/api/v0/expression.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6e, 0x9b, 0x4a,
	0x10, 0xc7, 0xc1, 0xf1, 0xe7, 0x10, 0xdb, 0xab, 0xd5, 0x49, 0x8e, 0xe3, 0x1c, 0x25, 0xc8, 0xd1,
	0xd1, 0xb1, 0x22, 0x1d, 0x9c, 0x92, 0x28, 0xf2, 0x55, 0x25, 0x13, 0x6f, 0x03, 0x2a, 0x01, 0x17,
	0x70, 0xfa, 0x71, 0x63, 0x99, 0x84, 0xd8, 0x48, 0x8e, 0x41, 0x7c, 0x44, 0xcd, 0x83, 0xf5, 0xbe,
	0x2f, 0xd1, 0x17, 0xe9, 0x13, 0x54, 0xbb, 0x18, 0x37, 0x5f, 0x6a, 0x7b, 0x35, 0xc3, 0x9f, 0xdf,
	0x0c, 0x9e, 0xff, 0x78, 0x17, 0xc4, 0xab, 0x69, 0x18, 0xa7, 0x0b, 0xaf, 0xdf, 0x9b, 0x86, 0x7e,
	0xef, 0xee, 0xa8, 0xe7, 0x7d, 0x0e, 0x23, 0x2f, 0x8e, 0xfd, 0x60, 0x29, 0x85, 0x51, 0x90, 0x04,
	0xb8, 0x99, 0x13, 0xd2, 0x34, 0xf4, 0xa5, 0xbb, 0xa3, 0xf6, 0xfe, 0x2c, 0x08, 0x66, 0x0b, 0xaf,
	0xc7, 0x5e, 0xbb, 0xe9, 0x4d, 0x2f, 0xf1, 0x6f, 0xbd, 0x38, 0x99, 0xde, 0x86, 0x59, 0x45, 0xe7,
	0x6b, 0x01, 0x4a, 0x97, 0xd3, 0x45, 0xea, 0x61, 0x09, 0x8a, 0xc9, 0x7d, 0xe8, 0xb5, 0x78, 0x91,
	0xef, 0x36, 0xe4, 0xb6, 0xf4, 0xa4, 0x95, 0xc4, 0x28, 0xe7, 0x3e, 0xf4, 0x2c, 0xc6, 0xe1, 0x03,
	0xd8, 0x8c, 0xfd, 0xd9, 0xd2, 0xbb, 0x9e, 0xdc, 0xd1, 0x37, 0x2d, 0x10, 0xf9, 0x2e, 0x56, 0x39,
	0x4b, 0xc8, 0xd4, 0xac, 0xe9, 0x7f, 0xd0, 0x48, 0x97, 0x8f, 0x30, 0x41, 0xe4, 0xbb, 0x45, 0x95,
	0xb3, 0xea, 0xb9, 0x9e, 0x81, 0xb4, 0x5b, 0x12, 0xf9, 0xcb, 0xd9, 0x0a, 0xdb, 0x14, 0xf9, 0x6e,
	0x8d, 0x75, 0x63, 0x6a, 0x06, 0xed, 0x03, 0xb8, 0x41, 0xb0, 0x58, 0x21, 0x75, 0x91, 0xef, 0x56,
	0x55, 0xce, 0xaa, 0x51, 0x6d, 0xdd, 0xe5, 0x3a, 0x48, 0xdd, 0x85, 0xb7, 0x42, 0x1a, 0x22, 0xdf,
	0xe5, 0x69, 0x97, 0x4c, 0xcd, 0x20, 0x02, 0xcd, 0xb5, 0x0b, 0x2b, 0xae, 0x29, 0xf2, 0x5d, 0x41,
	0x6e, 0x4b, 0x99, 0x5b, 0x52, 0xee, 0x96, 0xe4, 0xe4, 0x9c, 0xca, 0x59, 0x8d, 0x75, 0x11, 0x6b,
	0xa3, 0x54, 0xa0, 0xc4, 0x8a, 0x3b, 0x73, 0xa8, 0x2a, 0xfe, 0x72, 0x1a, 0xdd, 0x9b, 0x21, 0xfe,
	0x1f, 0x36, 0x16, 0xf3, 0x98, 0x79, 0x28, 0xc8, 0xbb, 0xcf, 0x3c, 0x24, 0xeb, 0x85, 0x59, 0x94,
	0xa3, 0x78, 0x34, 0x8f, 0x5b, 0x85, 0x3f, 0xc0, 0xa3, 0x79, 0xdc, 0xf9, 0xbe, 0x01, 0xf0, 0x53,
	0xc3, 0xaf, 0x1f, 0x6d, 0xec, 0xf0, 0x17, 0xe5, 0x0f, 0xd2, 0x07, 0x1b, 0x14, 0x01, 0xfc, 0x6b,
	0x6f, 0x99, 0xf8, 0x37, 0xbe, 0x17, 0xb1, 0xfd, 0x51, 0xc7, 0x1f, 0x68, 0x58, 0x5a, 0xcd, 0xc8,
	0xb6, 0x26, 0xc8, 0xdb, 0x2f, 0xff, 0x29, 0x54, 0xce, 0xca, 0x30, 0xdc, 0x87, 0x9a, 0xcb, 0xac,
	0x98, 0x04, 0x21, 0x5b, 0xa1, 0x20, 0xef, 0x3c, 0xab, 0xc9, 0xcd, 0x52, 0x39, 0xab, 0xea, 0xe6,
	0xc6, 0xf5, 0xa1, 0x9a, 0xe6, 0x85, 0xf5, 0xdf, 0xda, 0xa1, 0x72, 0x56, 0x25, 0xcd, 0x2a, 0x3b,
	0xdf, 0x78, 0x68, 0x3c, 0x1e, 0x0f, 0xef, 0x41, 0x9b, 0x7c, 0x18, 0x59, 0xc4, 0xb6, 0x35, 0xd3,
	0x70, 0x3e, 0x8e, 0xc8, 0x64, 0x6c, 0xd8, 0x23, 0x72, 0xa6, 0xbd, 0xd1, 0xc8, 0x10, 0x71, 0xb8,
	0x01, 0xa0, 0x0d, 0x89, 0xe1, 0xd0, 0x67, 0x0b, 0xf1, 0xb8, 0x06, 0xa5, 0xcb, 0x81, 0x3e, 0x26,
	0xa8, 0x80, 0x9b, 0x20, 0xe8, 0xe6, 0xb9, 0x76, 0x36, 0xd0, 0x27, 0x03, 0x63, 0x88, 0x80, 0xb2,
	0xb9, 0x60, 0x5a, 0x48, 0xc0, 0x65, 0x28, 0x90, 0x77, 0xe8, 0x2f, 0x1a, 0x0d, 0x82, 0xb6, 0x68,
	0xd4, 0x1d, 0xb4, 0xcd, 0x22, 0x41, 0x7f, 0xd3, 0x78, 0xee, 0xa0, 0x16, 0x8b, 0x04, 0xed, 0xe0,
	0x2a, 0x14, 0x75, 0xed, 0x2d, 0x41, 0x6d, 0x2c, 0x40, 0x45, 0xb3, 0x27, 0xc6, 0x58, 0xd7, 0xd1,
	0x2e, 0xfd, 0x0e, 0x7d, 0x30, 0x9d, 0x4c, 0xf8, 0x87, 0x0a, 0x8a, 0xe6, 0xbc, 0xd7, 0x6c, 0xc2,
	0x3e, 0xbc, 0xa7, 0x94, 0xa1, 0x48, 0xcf, 0xf7, 0xe1, 0x17, 0x1e, 0x6a, 0xeb, 0xb3, 0x87, 0x77,
	0x60, 0x8b, 0xfd, 0xd4, 0x17, 0xa6, 0x02, 0x28, 0xdb, 0x8e, 0xa5, 0x19, 0xe7, 0xd9, 0x44, 0xb6,
	0x66, 0x38, 0x7d, 0x54, 0x60, 0xb2, 0x66, 0x38, 0xaf, 0x4e, 0xd1, 0x46, 0x9e, 0x1f, 0xcb, 0xa8,
	0x98, 0xe7, 0xa7, 0x27, 0xa8, 0x44, 0xf1, 0x31, 0xc3, 0xcb, 0x54, 0x1e, 0x67, 0x78, 0x25, 0xcf,
	0x8f, 0x65, 0x54, 0xcd, 0xf3, 0xd3, 0x13, 0x54, 0xa3, 0x33, 0x29, 0xa6, 0xa9, 0x23, 0xa0, 0xea,
	0xd0, 0x1c, 0x2b, 0x3a, 0x41, 0x02, 0xae, 0x43, 0xcd, 0xd1, 0x2e, 0x88, 0xed, 0x0c, 0x2e, 0x46,
	0x68, 0x53, 0xf9, 0xf7, 0xd3, 0xc1, 0xcc, 0x4f, 0xe6, 0xa9, 0x2b, 0x5d, 0x05, 0xb7, 0xbd, 0xf5,
	0xd5, 0xf5, 0xe4, 0x0e, 0x73, 0xcb, 0xec, 0xb0, 0x1d, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x45,
	0x4c, 0x00, 0x52, 0xdd, 0x04, 0x00, 0x00,
}
