// Copyright 2017 Capsule8, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sensor

import (
	"github.com/capsule8/capsule8/pkg/expression"
	"github.com/capsule8/capsule8/pkg/sys/perf"
)

// FileOpenEventTypes defines the field types that can be used with filters
// on file open telemetry events.
var FileOpenEventTypes = expression.FieldTypeMap{
	"filename": expression.ValueTypeString,
	"flags":    expression.ValueTypeSignedInt32,
	"mode":     expression.ValueTypeSignedInt32,
}

// FileOpenTelemetryEvent is a telemetry event generated by the file event
// source.
type FileOpenTelemetryEvent struct {
	TelemetryEventData

	Filename string
	Flags    int32
	Mode     int32
}

// CommonTelemetryEventData returns the telemtry event data common to all
// telemetry events for a chargen telemetry event.
func (e FileOpenTelemetryEvent) CommonTelemetryEventData() TelemetryEventData {
	return e.TelemetryEventData
}

const (
	fsDoSysOpenKprobeAddress   = "do_sys_open"
	fsDoSysOpenKprobeFetchargs = "filename=+0(%si):string flags=%dx:s32 mode=%cx:s32"
)

func (s *Subscription) decodeDoSysOpen(
	sample *perf.SampleRecord,
	data perf.TraceEventSampleData,
) (interface{}, error) {
	var e FileOpenTelemetryEvent
	if !e.InitWithSample(s.sensor, sample, data) {
		return nil, nil
	}
	e.Filename = data["filename"].(string)
	e.Flags = data["flags"].(int32)
	e.Mode = data["mode"].(int32)
	return e, nil
}

// RegisterFileOpenEventFilter registers a file open event filter with a
// subscription.
func (s *Subscription) RegisterFileOpenEventFilter(filter *expression.Expression) {
	s.registerKprobe(fsDoSysOpenKprobeAddress, false,
		fsDoSysOpenKprobeFetchargs, s.decodeDoSysOpen,
		filter, FileOpenEventTypes)
}
